### ISSUE TITLE
Package does nothing

### ISSUE THREAD

**Issue by advaitju** [eveningkid/yakalelo#1]
I don't understand. I installed from settings and this package doesn't do anything.

**Comment by eveningkid** [comment]
Hi @advaitju,

<img src="https://media.giphy.com/media/xUA7aSk3jO6nvt7Vrq/giphy.gif" />

This package brings a command shortcut to replace your lorem ipsum with yakalelo lyrics.
Nothing else. So yes, close to nothingness in a sense. 😶

**Comment by advaitju** [comment]
Woops! :sweat_smile: just had to restart Atom. The package is pretty funny btw :+1:
